POST http://localhost:3000/api/v1/users
Content-Type: application/json

{
  "userName": "kevin25",
  "email": "kevinrugeles25",
  "password": "12345" 
}

###
GET  http://localhost:3000/api/v1/users/65087d45fe11221c1b3e2001