POST http://localhost:3000/api/v1/users
Content-Type: application/json

{
  "userName": "kevin25",
  "email": "kevinrugeles25",
  "password": "12345" 
}
###
GET http://localhost:3001/api/v1/users/kevin


###
GET  http://localhost:3001/api/v1/users

###
POST  http://localhost:3001/api/v1/auth
Content-Type: application/json

{
  "id": "a70f3f99-a4c2-45a7-96db-9a9712dae4f8",
  "userName": "kevinstivenr",
  "email": "kevinrugeles28@gmail.com",
  "role": ["TECNICO", "USER"],
  "password": "12345623",
  "sql": "select * from users"
}